name: Build Game

on:
  push: 
    branches:
    - master

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Gets semantic release info
        id: semantic_release_info
        uses: jossef/action-semantic-release-info@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: "Show semantic release data"
        run: |
          echo "Tag: ${{ steps.semantic_release_info.outputs.git_tag }}"
          echo "Channel: ${{ steps.semantic_release_info.outputs.channel }}"
          echo "Type: ${{ steps.semantic_release_info.outputs.type }}"
          echo "Head: ${{ steps.semantic_release_info.outputs.git_head }}"
          echo "Version: ${{ steps.semantic_release_info.outputs.version }}"
          echo "Name: ${{ steps.semantic_release_info.outputs.name }}"
          echo "Notes: ${{ steps.semantic_release_info.outputs.notes }}"                  
      - name: "cat package.json"
        run: cat ./package.json
      - name: Update package.json version
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: version
          value: ${{ steps.semantic_release_info.outputs.git_tag }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "create zip archive"
        run: |
          zip -r "${{ steps.semantic_release_info.outputs.git_tag }}.zip" release/
          ls -a
        # For deploy build as maven package
      - name: Publish package
        uses: actions/composite-actions@main
        with:
           version: ${{steps.semantic_release_info.outputs.version}}
           file: ${{steps.semantic_release_info.outputs.git_tag}}
        # run: |
        #  mvn \
        #  deploy:deploy-file \
        #  -DgroupId=alex \
        #  -DartifactId=test \
        #  -Dversion=${{ steps.semantic_release_info.outputs.version }} \
        #  -Dpackaging=zip \
        #  -Dfile="${{steps.semantic_release_info.outputs.git_tag}}.zip" \
        #  -DrepositoryId="github" \
        #  -Durl="https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
      - name: Make a changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          #git checkout -b release
          cd release
          echo "Test 1 ${GITHUB_ACTOR} ${GITHUB_REF}" >> gitpropertyes.txt
          echo "${{ github.event.head_commit.message }}" >> gitpropertyes.txt
          echo "${{ github.ref}}" >> gitpropertyes.txt
          cat gitpropertyes.txt
          rm -f random.txt
          rm -f test.yml
          ls -a
          git add .
          git status
          #git commit -m "Add changes" -a

      - name: Push changes
        #uses: ad-m/github-push-action@master
        uses: actions-js/push@master
        with:
          tag_name: ${{ steps.semantic_release_info.outputs.git_tag }}
          release_name: ${{ steps.semantic_release_info.outputs.git_tag }}
          body: ${{ steps.semantic_release_info.outputs.notes }}
          draft: false
          prerelease: false         
      # - name: NodeJS setup
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "12.x"
      # - name: "Automated Version Bump"
      #   uses: "phips28/gh-action-bump-version@master"
      #   with:
      #     tag-prefix: ''
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      # - name: "cat package.json"
      #   run: cat ./package.json         
      # - name: Make a changes
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     #git checkout -b release
      #     cd release
      #     echo "Test 1 ${GITHUB_ACTOR} ${GITHUB_REF}" >> gitpropertyes.txt
      #     echo "${{ github.event.head_commit.message }}" >> gitpropertyes.txt
      #     echo "${{ github.ref}}" >> gitpropertyes.txt
      #     cat gitpropertyes.txt
      #     rm -f random.txt
      #     rm -f test.yml
      #     ls -a
      #     git add .
      #     git status
      #     #git commit -m "Add changes" -a

  #     - name: Push changes
  #       #uses: ad-m/github-push-action@master
  #       uses: actions-js/push@master
  #       with:
  #         message: ${{ github.event.head_commit.message }}
  #         # directory: release
  #         force: true
  #         github_token: ${{ secrets.TOKEN }}
  #         branch: release
  # game-release:
  #   runs-on: ubuntu-latest
  #   needs: ["build-release"]
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #       with:
  #         ref: release
  #     - name: List Files  
  #       run: |
  #        ls -a
      #  # with:
      #  #   token: ${{ secrets.TOKEN}}
      #  #   fetch-depth: 0
      # - name: NodeJS setup
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "12.x" 
      # - run: echo "${GITHUB_REF}"       
      # - name: Create a Release
      #   run: npx semantic-release
      #   env:
      #   #the token have to be added to the sectrets
      #     GITHUB_TOKEN : ${secrets.TOKEN}
